---
- name: "Install Podman and dependencies"
  become: yes
  dnf:
    name:
      - podman
      - python3-libselinux

- name: "Add explicit cgroupfs configuration"
  become: yes
  blockinfile:
    mode: 0644
    create: true
    path: /etc/containers/containers.conf
    block: |
      [engine]
      cgroup_manager = "cgroupfs"

- name: "Enable Podman socket"
  become: yes
  become_user: "{{ podman_user }}"
  systemd:
    name: "podman.socket"
    state: started
    scope: user
    enabled: yes
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podman_user_uid }}"
