namespace: zedr
name: gitlab_runner
version: 1.4.0
readme: README.md
authors:
  - Rigel Di Scala <zedr@zedr.com>
description: Run a rootless Gitlab Runner using Podman.
license:
  - BSD-3-Clause
license_file: ''
tags:
  - gitlab
dependencies: {}
repository: https://github.com/zedr/gitlab_runner
documentation: ''
homepage: https://github.com/zedr/gitlab_runner
issues: https://github.com/zedr/gitlab_runner/issues
build_ignore:
  - .vagrant
  - .env
  - .gitignore
  - .idea
  - .cache
  - build
  - ansible_collections
  - Vagrantfile
  - init.yml
  - Makefile

